{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "fenix-api",
    "version": "0.1.0+mc26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-command",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-config",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-core",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-event",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-network",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-registry",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-resource",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-api-0.1.0+mc26.2.jar",
          "url": "fenix-api-0.1.0+mc26.2.jar",
          "size": 117785,
          "sha512": "0ffaf907afc4900053fdf47f98e5bb8ddb0adcefbf4bba8857da615d13634e1d74a8d88ca359746005d01e4955b0c1ceb9e604b6030d7cc2b4c6e7946b23c7f6",
          "sha256": "e92a94063e6bc9cf551616cd6deecb355829723aba19ffc0e391fd495c5f9258",
          "sha1": "15ed4f4bada367598bd5967a1a494620a7e472d2",
          "md5": "d1c99856925cbc8d6889d5d1bd1f7c39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-command",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-config",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-core",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-event",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-network",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-registry",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-resource",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-api-0.1.0+mc26.2.jar",
          "url": "fenix-api-0.1.0+mc26.2.jar",
          "size": 117785,
          "sha512": "0ffaf907afc4900053fdf47f98e5bb8ddb0adcefbf4bba8857da615d13634e1d74a8d88ca359746005d01e4955b0c1ceb9e604b6030d7cc2b4c6e7946b23c7f6",
          "sha256": "e92a94063e6bc9cf551616cd6deecb355829723aba19ffc0e391fd495c5f9258",
          "sha1": "15ed4f4bada367598bd5967a1a494620a7e472d2",
          "md5": "d1c99856925cbc8d6889d5d1bd1f7c39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-api-0.1.0+mc26.2-sources.jar",
          "url": "fenix-api-0.1.0+mc26.2-sources.jar",
          "size": 1039,
          "sha512": "4723a5552944aaa1da15018b55f636f8238ef9aeef50bf3fc73634306615e1fe73126b70e7fac7487002324ba899f1d5c2a2ffd9b1eb3699200ff53fad497b0f",
          "sha256": "48922e2865309debba4f783b1e1dfa2dbb96b004bf145488373b5473240c4b50",
          "sha1": "e4ce16adf3ee1b1239d869105851bf00738ba819",
          "md5": "1f2954cd3a59caf04b5b313ca46bc496"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-api-0.1.0+mc26.2-javadoc.jar",
          "url": "fenix-api-0.1.0+mc26.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
