{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "fenix-api-event",
    "version": "0.3.0+mc26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-core",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-api-event-0.3.0+mc26.2.jar",
          "url": "fenix-api-event-0.3.0+mc26.2.jar",
          "size": 49633,
          "sha512": "3b32433455412c09d571b24c668fb04dd8cbf5d500c202ce491b5928cd1f16f71993155939a906ba747b59e3845d403e05dfd349e0bb4868c62b446ceae1dac5",
          "sha256": "8cbe4dc920721651b37ffe345a5e190027fa2270781dface39cbbe2908e91e36",
          "sha1": "c9e94f7b3eeef65f00c2d9b2880accebf1cf2776",
          "md5": "e3a3d5a4a98e86627c3f421325d0456f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-core",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-api-event-0.3.0+mc26.2.jar",
          "url": "fenix-api-event-0.3.0+mc26.2.jar",
          "size": 49633,
          "sha512": "3b32433455412c09d571b24c668fb04dd8cbf5d500c202ce491b5928cd1f16f71993155939a906ba747b59e3845d403e05dfd349e0bb4868c62b446ceae1dac5",
          "sha256": "8cbe4dc920721651b37ffe345a5e190027fa2270781dface39cbbe2908e91e36",
          "sha1": "c9e94f7b3eeef65f00c2d9b2880accebf1cf2776",
          "md5": "e3a3d5a4a98e86627c3f421325d0456f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-api-event-0.3.0+mc26.2-sources.jar",
          "url": "fenix-api-event-0.3.0+mc26.2-sources.jar",
          "size": 21310,
          "sha512": "59414ca848760d5e3a56d32785a733c7f1e60d4469b8f22ef8da6ec3f0a99982930478592abe4f0df9ed6ff558fb514c41dd325f34d384541429a82058bb1b5f",
          "sha256": "0672e5b66bcfec547cbe34a24ad99c69b350611fe3c45a63f22f990d15243bc0",
          "sha1": "6543f9b810a92860135aa5dfd7d58f2e16bdfb6d",
          "md5": "8c1e30439efbd9590913cde4b9e7669d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-api-event-0.3.0+mc26.2-javadoc.jar",
          "url": "fenix-api-event-0.3.0+mc26.2-javadoc.jar",
          "size": 4257933,
          "sha512": "14b736b14511b59126b2bcbe8d91d7380c030e0b9e308f8a72a724ad4fd3901bf2d1611702ec868cd61bd2202c4153b49ac36d1e5507bcd19a44c7acf5be01ad",
          "sha256": "29f3626cb47e866c2fa00e2b9253c2fb87943e8bc1e87d651b782da11bfd4f09",
          "sha1": "721cd9010e3a68fdb6276d5c4822d55ceebe3d26",
          "md5": "a9c4ab59bc116b3e37c94db37e09660e"
        }
      ]
    }
  ]
}
