{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "fenix-installer",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fenix-installer-0.1.2.jar",
          "url": "fenix-installer-0.1.2.jar",
          "size": 1858747,
          "sha512": "67e3c2a3ae95a8f460a38db2fa75d5cd0447ec8b81060b20dec9fabab885c9b5022ca076ea2b7fe23e3df78c0fce7bd5dc3c9af475af97b0e40018de4833ab45",
          "sha256": "b5b1148c02608e6d8ca6655f9d1dcf81dbcda27ba922b53134e8c5385b66dcfe",
          "sha1": "a1fab22180b70b81dc4873dc69641c9cf773aca3",
          "md5": "9b1d7ac143d45d505073f3cd58024653"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-installer-0.1.2.jar",
          "url": "fenix-installer-0.1.2.jar",
          "size": 1858747,
          "sha512": "67e3c2a3ae95a8f460a38db2fa75d5cd0447ec8b81060b20dec9fabab885c9b5022ca076ea2b7fe23e3df78c0fce7bd5dc3c9af475af97b0e40018de4833ab45",
          "sha256": "b5b1148c02608e6d8ca6655f9d1dcf81dbcda27ba922b53134e8c5385b66dcfe",
          "sha1": "a1fab22180b70b81dc4873dc69641c9cf773aca3",
          "md5": "9b1d7ac143d45d505073f3cd58024653"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-installer-0.1.2-sources.jar",
          "url": "fenix-installer-0.1.2-sources.jar",
          "size": 12680,
          "sha512": "88f551454b08ecdf01e3d128e0b1a32f6003c2ad5c5b3cfd94b4065a12e08e39bafec7a9815b2ec726587752be27ffb7ecf2632711307f8b671ce3213a0956df",
          "sha256": "324de9569d556ceec9d8959a70193e04389bc62777d09a1978878f4633a4854f",
          "sha1": "34c9f0250268a96af544c0f42b9ae799889ca7d4",
          "md5": "5e74d907b3aad03d659a2547ecf8646e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-installer-0.1.2-javadoc.jar",
          "url": "fenix-installer-0.1.2-javadoc.jar",
          "size": 4163760,
          "sha512": "6e8e97a970e4b23147023716c26c227bcf2f16b22e04f54e55f6841874d07ea319d34869433964c5e61d7365d5003f12f7a7ee84bac76d140e2eef45604b9bd3",
          "sha256": "0a3af5c645930a1869adaeefd4f9bbea78cfd8c8373ebefce067fbae7aca2057",
          "sha1": "2ded0510ab74c2350b432ce9d990f2d752f6365a",
          "md5": "f13d68294fc031e0e7ffbbfd415005c6"
        }
      ]
    }
  ]
}
