{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "ember",
    "version": "0.6.0+mc26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-core",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-registry",
          "version": {
            "requires": "0.7.0+mc26.2"
          }
        }
      ],
      "files": [
        {
          "name": "ember-0.6.0+mc26.2.jar",
          "url": "ember-0.6.0+mc26.2.jar",
          "size": 107173,
          "sha512": "07c80b34e92c75d2c19a5318376c45a13a7d986c514a3b08598f23c1aa167dfa299d31cccd32f3815d226445ec07b3dbb959e7aa350cc73b1e41c36325c03251",
          "sha256": "47b5d517a10312b4cfcdc11b124ec605ce74156dac76c8a77ea46f64ddbbeb57",
          "sha1": "36cecffef0bd057ede485b5a495917ec8db66f9c",
          "md5": "d6aba76d6d04e42afbe75a53a11e99aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-core",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-registry",
          "version": {
            "requires": "0.7.0+mc26.2"
          }
        }
      ],
      "files": [
        {
          "name": "ember-0.6.0+mc26.2.jar",
          "url": "ember-0.6.0+mc26.2.jar",
          "size": 107173,
          "sha512": "07c80b34e92c75d2c19a5318376c45a13a7d986c514a3b08598f23c1aa167dfa299d31cccd32f3815d226445ec07b3dbb959e7aa350cc73b1e41c36325c03251",
          "sha256": "47b5d517a10312b4cfcdc11b124ec605ce74156dac76c8a77ea46f64ddbbeb57",
          "sha1": "36cecffef0bd057ede485b5a495917ec8db66f9c",
          "md5": "d6aba76d6d04e42afbe75a53a11e99aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ember-0.6.0+mc26.2-sources.jar",
          "url": "ember-0.6.0+mc26.2-sources.jar",
          "size": 62426,
          "sha512": "045977a7c303bd35a80e75d657eadcb19737d075d124530950a05b4d252c385b5c39007debcae253dca13cef9cdd83a7406083241d270931f28251ee09f1e402",
          "sha256": "a3d74b764776acf7e14a9a9d2e41f7e61f4a701e4a0a4fcc815a24902806332f",
          "sha1": "672305e90072d3c13601067ab14ceece5aff32f9",
          "md5": "11a012ac8408413cc3e2051089a507be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ember-0.6.0+mc26.2-javadoc.jar",
          "url": "ember-0.6.0+mc26.2-javadoc.jar",
          "size": 4378375,
          "sha512": "bb88f87817288507b683b0e26df8427c59ceb7933805410796050a5d78971d0504520bcb26dbdb2b3e31124915633bf414273e152084731062e475c90721cb4a",
          "sha256": "796c707f6d0a841ad7fd0bb184676b412f1c1ef6af85a57fee4dcb8ca2dd2434",
          "sha1": "5d20c0489da3a2c4511b20b20e49d53b2917d543",
          "md5": "dfefb935af01207d20d03f45a59f09d5"
        }
      ]
    }
  ]
}
