{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "fenix-api",
    "version": "0.1.3+mc26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-command",
          "version": {
            "requires": "0.1.1+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-config",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-core",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-event",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-network",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-registry",
          "version": {
            "requires": "0.1.2+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-resource",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-api-0.1.3+mc26.2.jar",
          "url": "fenix-api-0.1.3+mc26.2.jar",
          "size": 139776,
          "sha512": "7692a7d49825679ad1f21f0e8ac094ec41e134864af560950aefdfafacfc2362a89a10bbc9722f1602c47dfa262b1e2866009c3939d666a29ad31ee76e38d4c5",
          "sha256": "f6aafe9284ffdb870507e80c6e786a92796bbb885ef5dcf1a7a7cd6a1421c501",
          "sha1": "c5ec9595990ef01c1bef2670be19f53c44739415",
          "md5": "88e593cee1b40785aedf020254ff3540"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-command",
          "version": {
            "requires": "0.1.1+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-config",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-core",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-event",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-network",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-registry",
          "version": {
            "requires": "0.1.2+mc26.2"
          }
        },
        {
          "group": "fr.d4emon.fenix",
          "module": "fenix-api-resource",
          "version": {
            "requires": "0.1.0+mc26.2"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-api-0.1.3+mc26.2.jar",
          "url": "fenix-api-0.1.3+mc26.2.jar",
          "size": 139776,
          "sha512": "7692a7d49825679ad1f21f0e8ac094ec41e134864af560950aefdfafacfc2362a89a10bbc9722f1602c47dfa262b1e2866009c3939d666a29ad31ee76e38d4c5",
          "sha256": "f6aafe9284ffdb870507e80c6e786a92796bbb885ef5dcf1a7a7cd6a1421c501",
          "sha1": "c5ec9595990ef01c1bef2670be19f53c44739415",
          "md5": "88e593cee1b40785aedf020254ff3540"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-api-0.1.3+mc26.2-sources.jar",
          "url": "fenix-api-0.1.3+mc26.2-sources.jar",
          "size": 1047,
          "sha512": "c0dea21a2f82f56d15e16e51c693f1717732b0036c2d1bf70675c83a63c62ae570de699af7a858476fdbe6356f276ee261a8dcf65389da14a010a6f89d7597bc",
          "sha256": "8c5e4ea35bfeb6b1443914c8e712e3d97bdaa6af83e39445a464c5ab3567880d",
          "sha1": "ce09cbb366622acd45eed81293fbc73655a3fb26",
          "md5": "4b97311c4e48bb0f6b113000c2cb6c58"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-api-0.1.3+mc26.2-javadoc.jar",
          "url": "fenix-api-0.1.3+mc26.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
