{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "fenix-gradle-plugin",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fenix-gradle-plugin-0.2.2.jar",
          "url": "fenix-gradle-plugin-0.2.2.jar",
          "size": 40969,
          "sha512": "2468d15684a644dbc265765cf94f9f54f27467244a29a735b5a2296891c902a9a99ccd1851b87a2b37ba661516cafca9f0e9e634b39b8ac327ed6a73c5a81e98",
          "sha256": "9e233a97d3a9eb59cbf4dc6ba57b8b59e6324c77c8fadd293045ca5f42300a09",
          "sha1": "0e18a0bc1dbed61ab64216053b8f9a7dd610a5aa",
          "md5": "66bfe8867c7913ad2c72c21b537b6285"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.vineflower",
          "module": "vineflower",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-gradle-plugin-0.2.2.jar",
          "url": "fenix-gradle-plugin-0.2.2.jar",
          "size": 40969,
          "sha512": "2468d15684a644dbc265765cf94f9f54f27467244a29a735b5a2296891c902a9a99ccd1851b87a2b37ba661516cafca9f0e9e634b39b8ac327ed6a73c5a81e98",
          "sha256": "9e233a97d3a9eb59cbf4dc6ba57b8b59e6324c77c8fadd293045ca5f42300a09",
          "sha1": "0e18a0bc1dbed61ab64216053b8f9a7dd610a5aa",
          "md5": "66bfe8867c7913ad2c72c21b537b6285"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-gradle-plugin-0.2.2-sources.jar",
          "url": "fenix-gradle-plugin-0.2.2-sources.jar",
          "size": 25105,
          "sha512": "d9ab24480430397f430ad44290ba18f0a24eb786de9dcd3876f95e31eb0c95e672b3c4f545fe5303f2a26cffc2c54826e27db2a81da1dc317563bef82c47f553",
          "sha256": "96d60f1dacb2c02ae031de37d17d5b67ce470cc981531c80896395d0e77346f2",
          "sha1": "f91e4419a907a9fc5320e24b1c6272111d30e791",
          "md5": "72ee54c521303c2f8cc5f40ad89682db"
        }
      ]
    }
  ]
}
