{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "fenix-gradle-plugin",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fenix-gradle-plugin-0.2.2.jar",
          "url": "fenix-gradle-plugin-0.2.2.jar",
          "size": 40969,
          "sha512": "58f08945a166ef29303f406bfebe8cf067ba110c9a49067d6e6f326a9f4d6cf058314fdc7419857e00c71db270bf25aec733286adea61ebd00224aa2aa4512ec",
          "sha256": "ea6a4437b58cf950ed729ddbcb9146c43cd75c492541d0cf1a82b2f92a279f0f",
          "sha1": "e9a7ed789acf6e8b4c6ee9e5f0f7b1f211c4a272",
          "md5": "aa3a8a880cd7810f77bd9dc293f0aee9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.vineflower",
          "module": "vineflower",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-gradle-plugin-0.2.2.jar",
          "url": "fenix-gradle-plugin-0.2.2.jar",
          "size": 40969,
          "sha512": "58f08945a166ef29303f406bfebe8cf067ba110c9a49067d6e6f326a9f4d6cf058314fdc7419857e00c71db270bf25aec733286adea61ebd00224aa2aa4512ec",
          "sha256": "ea6a4437b58cf950ed729ddbcb9146c43cd75c492541d0cf1a82b2f92a279f0f",
          "sha1": "e9a7ed789acf6e8b4c6ee9e5f0f7b1f211c4a272",
          "md5": "aa3a8a880cd7810f77bd9dc293f0aee9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-gradle-plugin-0.2.2-sources.jar",
          "url": "fenix-gradle-plugin-0.2.2-sources.jar",
          "size": 25105,
          "sha512": "d9ab24480430397f430ad44290ba18f0a24eb786de9dcd3876f95e31eb0c95e672b3c4f545fe5303f2a26cffc2c54826e27db2a81da1dc317563bef82c47f553",
          "sha256": "96d60f1dacb2c02ae031de37d17d5b67ce470cc981531c80896395d0e77346f2",
          "sha1": "f91e4419a907a9fc5320e24b1c6272111d30e791",
          "md5": "72ee54c521303c2f8cc5f40ad89682db"
        }
      ]
    }
  ]
}
