{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "fenix-gradle-plugin",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fenix-gradle-plugin-0.3.0.jar",
          "url": "fenix-gradle-plugin-0.3.0.jar",
          "size": 42081,
          "sha512": "26c8a7dab226bd1ccf3d7145c577cf381dd1f039ef6aae96f133b60d3716e40fc403eca3f912c3e32325fcf97efcc82bdd5d795a826536d61cabda3aa474dbcf",
          "sha256": "0c21f19235e1f8a7c790a003d415de0ea1a5507d56743560f2e2047bc81162cf",
          "sha1": "5a15f9a2496ceec3494f0cb220a315c2d9f82988",
          "md5": "5251a5499b647558e833219fb50eb656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.vineflower",
          "module": "vineflower",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-gradle-plugin-0.3.0.jar",
          "url": "fenix-gradle-plugin-0.3.0.jar",
          "size": 42081,
          "sha512": "26c8a7dab226bd1ccf3d7145c577cf381dd1f039ef6aae96f133b60d3716e40fc403eca3f912c3e32325fcf97efcc82bdd5d795a826536d61cabda3aa474dbcf",
          "sha256": "0c21f19235e1f8a7c790a003d415de0ea1a5507d56743560f2e2047bc81162cf",
          "sha1": "5a15f9a2496ceec3494f0cb220a315c2d9f82988",
          "md5": "5251a5499b647558e833219fb50eb656"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-gradle-plugin-0.3.0-sources.jar",
          "url": "fenix-gradle-plugin-0.3.0-sources.jar",
          "size": 25874,
          "sha512": "c2d696b5a676fedc647c3c5862b8d0378b9e6c4bbef811229e959b2f992b31731afa2cd80baac5e9f56a9633e61c7858c1b1989afafa97867e1e43a7caa3c720",
          "sha256": "56d701b3a9b60f532ee2de09cc4cf089317c013d38a68e2c0dd78cac6fdccf8b",
          "sha1": "158ab7f672efb4b0b5c5b209c8768642376a66f3",
          "md5": "97e5fff24e3a70ffd67a9d7aca9e0fb6"
        }
      ]
    }
  ]
}
