{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.d4emon.fenix",
    "module": "fenix-gradle-plugin",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fenix-gradle-plugin-0.3.0.jar",
          "url": "fenix-gradle-plugin-0.3.0.jar",
          "size": 42080,
          "sha512": "420c57e0d0b9b316a1db5965e80e1aca8735d4c61b6b9fd51e813c870ca659c70c27d78242865ef167659506135a94676e165039353f3fa7cd13a6c7c9de9909",
          "sha256": "32bccaf47ff180159aca5a34f27a26375350f96881b7420a1df0edcbf118db00",
          "sha1": "70a9acf8dedd35ae7d6c68384bccf4101435924a",
          "md5": "c8123a2fcecaa66276063ff9c0694919"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.vineflower",
          "module": "vineflower",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "fenix-gradle-plugin-0.3.0.jar",
          "url": "fenix-gradle-plugin-0.3.0.jar",
          "size": 42080,
          "sha512": "420c57e0d0b9b316a1db5965e80e1aca8735d4c61b6b9fd51e813c870ca659c70c27d78242865ef167659506135a94676e165039353f3fa7cd13a6c7c9de9909",
          "sha256": "32bccaf47ff180159aca5a34f27a26375350f96881b7420a1df0edcbf118db00",
          "sha1": "70a9acf8dedd35ae7d6c68384bccf4101435924a",
          "md5": "c8123a2fcecaa66276063ff9c0694919"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fenix-gradle-plugin-0.3.0-sources.jar",
          "url": "fenix-gradle-plugin-0.3.0-sources.jar",
          "size": 25874,
          "sha512": "c2d696b5a676fedc647c3c5862b8d0378b9e6c4bbef811229e959b2f992b31731afa2cd80baac5e9f56a9633e61c7858c1b1989afafa97867e1e43a7caa3c720",
          "sha256": "56d701b3a9b60f532ee2de09cc4cf089317c013d38a68e2c0dd78cac6fdccf8b",
          "sha1": "158ab7f672efb4b0b5c5b209c8768642376a66f3",
          "md5": "97e5fff24e3a70ffd67a9d7aca9e0fb6"
        }
      ]
    }
  ]
}
